version: "3.8"

services:
  n8n:
    image: n8nio/n8n:1.90.2
    volumes:
      - n8n_data:/home/node/.n8n
    hostname: n8n
    container_name: n8n
    ports:
      - "5678:5678"
    restart: always
    depends_on:
      - mcp_server
    networks:
      - net_n8n
  mcp_server:
    image: mcp-server:1.0
    build:
      context: ./src
      dockerfile: Dockerfile
    volumes:
      - mcp_server:/opt/mcp_server
    hostname: mcp_server
    container_name: mcp_server
    restart: always
    networks:
      - net_n8n
volumes:
  n8n_data:
    driver: local
    driver_opts:
      type: none
      device: $PWD/n8n_data
      o: bind
  mcp_server:
    driver: local
    driver_opts:
      type: none
      device: $PWD/mcp_server
      o: bind
networks:
  net_n8n:
    driver: bridge
    ipam:
      config:
        - subnet: 10.1.2.0/24
